# Generated by Django 3.2.6 on 2022-01-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemaker', '0002_auto_20220106_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, null=True),
        ),
    ]
